wardenslog/wardens/urls.py
from django.conf.urls import url
from . import views
from wardens.views import (login_view, logout_view)

urlpatterns = [
    # url(r'^log$', views.UserFormView.as_view(), name='log'),       #Currently after wardens page i.e /wardens/log
    url(r'^$', views.index, name='index'),
    url(r'^incident/$', views.incident, name='incident'),
    url(r'^incident/form/$', views.incident_form, name='incident_form'),
    url(r'^cases/$', views.cases, name='closed'),
    url(r'^login/$', views.login_view, name='login'),
    url(r'^logout/$', views.logout_view, name='logout'),
    url(r'^required/$', views.required, name='required'),
    url(r'^taken/$', views.taken, name='taken'),
    url(r'^detail/(?P<pk>[0-9]+)/$', views.detail, name='detail'),
    url(r'^update/(?P<pk>[0-9]+)/$', views.update, name='update'),

]

wardenslog/wardenslog/urls.py
from django.conf.urls import include, url
from django.contrib import admin

urlpatterns = [
    url(r'^i18n/', include('django.conf.urls.i18n')),
    url(r'^admin/', admin.site.urls),               #Make sure there URLs are ok
    url(r'^wardens/', include('wardens.urls')),
    url('^', include('django.contrib.auth.urls')),
]

wardenslog/wardens/models.py
from __future__ import unicode_literals
from django.utils.translation import ugettext_lazy as _

from django.db import models


class Site(models.Model):   #site model containing all relevant information regarding site
    name = models.CharField(_('Name'), max_length=100)

    def __str__(self):
        return self.name


class Hall(models.Model):   #Hall model containing all relevant information regarding student
    name = models.CharField(_('Name'), max_length=40)
    site = models.ForeignKey(Site, related_name='halls')

    def __str__(self):
        return self.name


class Student(models.Model):                        #student model. containing all relevant information regarding student
    banner_id = models.CharField(_('banner id'), max_length=12)
    surname = models.CharField(_('surname'), max_length=60)
    forename = models.CharField(_('forename'), max_length=60)
    site = models.CharField(_('Site'), max_length=30)
    hall = models.CharField(_('Hall'), max_length=30)
    room_number = models.CharField(_('Room Number'), max_length=50)

    def __str__(self):
        return '%s %s' % (self.surname, self.forename)


class IncidentType(models.Model):   #Model for the type of incident at hand
    type = models.CharField(_('Type'), max_length=50)

    def __str__(self):
        return self.type


class Incident(models.Model):       # all fields related to creating an incident report and/or viewing cases i.e closed
    title = models.CharField(_('title'), max_length=100)
    date_created = models.DateTimeField(auto_now_add=True)
    date_modified = models.DateTimeField(auto_now=True)
    warden_name = models.CharField(_('warden name'), max_length=150)
    senior_warden = models.CharField(_('senior warden'), max_length=150)
    site = models.ForeignKey(Site, related_name='incidents')
    halls = models.ForeignKey(Hall, related_name='incidents')
    incident_type = models.ForeignKey(IncidentType, related_name='incidents')
    ACTIVE = 'Active'
    CLOSED = 'Closed'
    CASE_STATUS = (
        (ACTIVE, 'Active'),
        (CLOSED, 'Closed'),
    )
    case_status = models.CharField(
        max_length=50,
        choices=CASE_STATUS,
        default=ACTIVE
    )
    description = models.TextField()
    notes_to = models.TextField(null=True, blank=True)
    notes_by = models.TextField(null=True, blank=True)
    YES = 'YES'
    NO = 'No'
    WARNING_ISSUED = (
        (YES, 'Yes'),
        (NO, 'No'),
    )
    warning_issued = models.CharField(
        null=True,
        max_length=50,
        choices=WARNING_ISSUED,
        default=YES
    )
    YES = 'Yes'
    NO = 'No'
    DISCIPLINARY_REQUIRED = (
        (YES, _('Yes')),
        (NO, _('No')),
    )
    disciplinary_required = models.CharField(
        null=True,
        max_length=50,
        choices=DISCIPLINARY_REQUIRED,
        default=YES
    )
    disciplinary_called_by = models.CharField(_('disciplinary called by'), max_length=150, null=True, blank=True)
    disciplinary_date = models.DateTimeField(_('disciplinary date'), null=True, blank=True)
    student = models.ForeignKey(Student, related_name='incidents')
    complainant = models.CharField(_('complainant'), max_length=500, null=True, blank=True)
    accomplices = models.CharField(_('accomplices'), max_length=500, null=True, blank=True)
    witnesses = models.CharField(_('witnesses'), max_length=500, null=True, blank=True)

wardenslog/wardens/forms.py
from django.forms import ModelForm
from wardens.models import Incident
from django.contrib.auth.models import User
from django import forms
from django.contrib.auth import (
    authenticate,
    get_user_model,
    login,
    logout,

)


class IncidentForm(ModelForm):
    class Meta:
        model = Incident
        fields = '__all__'
        exclude = ['date_created', ]

    def save(self, commit=True):
        obj = super(IncidentForm, self).save(commit=False)
        if obj.disciplinary_required == 0:
            obj.disciplinary_date = ''
            obj.called_by = ''

        obj.save()


User = get_user_model()


class UserLoginForm(forms.Form):
    username = forms.CharField()
    password = forms.CharField(widget=forms.PasswordInput)

    def clean(self, *args, **kwargs):
        username = self.cleaned_data.get("username")
        password = self.cleaned_data.get("password")
        user = authenticate(username=username, password=password)

        if username and password:
            user = authenticate(username=username, password=password)
            if not user:
                raise forms.ValidationError("This user does not exist")
            if not user.check_password(password):
                raise forms.ValidationError("Incorrect password")
            if not user.is_active:
                raise forms.ValidationError("This user is not active")

        return super(UserLoginForm, self).clean(*args, **kwargs)

wardenslog/wardens/views.py
from django.utils.translation import ugettext as _
from django.contrib.auth.decorators import login_required
from django.http import HttpResponse, HttpResponseRedirect
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib import messages
from django.http import Http404
from .forms import IncidentForm
from django.views.generic.edit import  UpdateView

from django.contrib.auth import (
    authenticate,
    get_user_model,
    login,
    logout,

)

from .forms import UserLoginForm
from .models import Incident


# from django.views.generic import View
# from .forms import UserForm

@login_required
def index(request):
    return render(request, 'wardens/wardens.html')


@login_required
def incident(request):
    return render(request, 'wardens/incident.html')


@login_required
def closed(request):
    return render(request, 'wardens/closed.html')


@login_required
def disciplinary_required(request):
    return render(request, 'wardens/required.html')


@login_required
def disciplinary_taken(request):
    return render(request, 'wardens/taken.html')


@login_required
def incident_form(request):
    form = IncidentForm(request.POST or None)

    # import pdb; pdb.set_trace()

    if form.is_valid():
        form.save()
        messages.add_message(request, messages.INFO, 'Saved')
        return redirect('incident_form')
    print form.errors
    return render(request, 'wardens/incident_form.html', {
        'form': form,
    })


def login_view(request):
    print(request.user.is_authenticated())
    title = "Login"
    form = UserLoginForm(request.POST or None)
    if form.is_valid():
        username = form.cleaned_data.get("username")  # one has double quotations other has single?
        password = form.cleaned_data.get('password')
        user = authenticate(username=username, password=password)
        login(request, user)
        return redirect("/wardens/")
    print(request.user.is_authenticated())  # not required in final project
    return render(request, "wardens/login.html", {"form": form, "title": title})


def logout_view(request):  # logs the user out and redirects to the 'thankyou' page
    logout(request)
    return redirect("/wardens/thankyou/")


@login_required
def cases(request):
    results = Incident.objects.all()
    print results
    return render(request, "wardens/closed.html", {"results": results})


@login_required
def required(request):
    results = Incident.objects.filter(disciplinary_required='Yes', ).exclude(case_status='Closed')
    print results
    return render(request, "wardens/required.html", {"results": results})


@login_required
def taken(request):
    results = Incident.objects.filter(disciplinary_required='Yes', case_status='Closed')
    print results
    return render(request, "wardens/taken.html", {"results": results})


@login_required
def detail(request, pk):
    try:
        incident = Incident.objects.get(pk=pk)      #get object or 404? reduce amounts of code
    except Incident.DoesNotExist:
        raise Http404("report does not exist")
    return render(request, 'wardens/detail.html', {'incident': incident})


@login_required
def update(request, pk):
    instance = get_object_or_404(Incident, pk=pk)
    form = IncidentForm(request.POST or None, instance=instance)
    if form.is_valid():
        form.save()
        return redirect('required')

    context = {
        "title": instance.title,
        "instance": instance,
        "form": form,
    }
    return render(request, "wardens/incident_form.html", context)

wardenslog/wardens/templates/wardens/base.html
{% load i18n %}
{% load bootstrap3 %}
<!DOCTYPE html>
<html lang="en" xmlns="http://www.w3.org/1999/html">
   <head>
      <meta http-equiv="X-UA-Compatible" content="IE=edge">
      <meta name="viewport" content="width=device-width, initial-scale=1">
      <script src="https://code.jquery.com/jquery-2.2.4.min.js" integrity="sha256-BbhdlvQf/xTY9gja0Dq3HiwQF8LaCRTXxZKRutelT44=" crossorigin="anonymous"></script>
      <!-- Latest compiled and minified CSS -->
      <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap.min.css" integrity="sha384-1q8mTJOASx8j1Au+a5WDVnPi2lkFfwwEAa8hDDdjZlpLegxhjVME1fgjWPGmkzs7" crossorigin="anonymous">
      <!-- Optional theme -->
      <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/css/bootstrap-theme.min.css" integrity="sha384-fLW2N01lMqjakBkx3l/M9EahuwpSfeNvV63J5ezn3uZzapT0u7EYsXMjQV+0En5r" crossorigin="anonymous">
      <!-- Latest compiled and minified JavaScript -->
      <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.6/js/bootstrap.min.js" integrity="sha384-0mSbJDEHialfmuBBQP6A4Qrprq5OVfW37PRR3j5ELqxss1yVqOtnepnHVP9aJ7xS" crossorigin="anonymous"></script>
      <script src="https://cdn.datatables.net/1.10.12/css/jquery.dataTables.min.css"></script>
      <script src="https://cdn.datatables.net/1.10.12/js/jquery.dataTables.min.js"></script>
      <script src="https://cdn.datatables.net/1.10.12/css/dataTables.bootstrap.min.css"></script>
      <script src="https://cdn.datatables.net/1.10.12/js/jquery.dataTables.min.js"></script>
      <script src="https://cdn.datatables.net/1.10.12/js/dataTables.bootstrap.min.js"></script>
      <title style="align-content: center">  {% trans 'Wardens Log' %} </title>
   </head>
   {% block paragraph %}
   {% endblock %}
   <body>
      {% block navbar %}
      <nav class="navbar navbar-inverse navbar-fixed-top">
         <div class="container">
            <div class="navbar-header">
               <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
               <span class="sr-only">Toggle navigation</span>
               <span class="icon-bar"></span>
               <span class="icon-bar"></span>
               <span class="icon-bar"></span>
               </button>
               <a class="navbar-brand" href="/wardens/">Home</a>
            </div>
            <div id="navbar" class="collapse navbar-collapse">
               <ul class="nav navbar-nav">
                  <li><a href="/wardens/incident/form/">Incident Form</a></li>
                  <li><a href="/wardens/required">Disciplinary required</a></li>
                  <li><a href="/wardens/taken/">Disciplinary taken</a></li>
                  <li><a href="/wardens/cases/">Cases</a></li>
                  <li><a href="/wardens/logout/"> Logout </a> </li>
               </ul>
            </div>
            <!--/.nav-collapse -->
         </div>
         </div>
      </nav>
      <div class="container" style="padding-top: 70px">
         {% endblock navbar %}

         <form id="form1" style="float: right" class="translate" action="{% url 'set_language' %}" method="post">{% csrf_token %}
            <input name="next" type="hidden" value="{{ redirect_to }}" />
            <select id="language" name="language">
            {% get_current_language as LANGUAGE_CODE %}
            {% get_available_languages as LANGUAGES %}
            {% get_language_info_list for LANGUAGES as languages %}
            {% for language in languages %}
            <option value="{{ language.code }}"{% if language.code == LANGUAGE_CODE %} selected="selected"{% endif %}>
            {{ language.name_local }} ({{ language.code }})
            </option>
            {% endfor %}
            </select>
            <input type="submit" value="Go" />
         </form>





         {% block content %}
         {% endblock %}

   </body>
</html>

wardenslog/wardens/templates/wardens/closed.html
{%  extends 'wardens/base.html' %}
{% load i18n %}

{% block content %}

    <table id="example" class="table table-striped table-bordered" cellspacing="0" width="100%">
    <thead>
        <tr>
        <th> {% trans 'Status' %} </td>
        <th> {% trans 'Title' %}  </th>
        <th> {% trans 'Date Created' %} </th>
        <th> {% trans 'Warden Name'%}</th>
        <th> {% trans 'View' %}</th>
    </tr>
    </thead>
    <tbody>
        {% for item in results %}
    <tr>
    <td>{{ item.case_status }}</td>
    <td>{{ item.title }}</td>
    <td>{{ item.date_created }}</td>
    <td>{{ item.warden_name }}</td>
    <td><a href="{% url 'detail' item.pk  %}">{% trans 'detail' %}</a></td>

    </tr>

    {% endfor %}
    </tbody>
    </table>
<script>
$(document).ready(function(){
   $('#example').DataTable();
});

</script>
{% endblock %}

wardenslog/wardens/templates/wardens/detail.html
{% extends 'wardens/base.html' %}
{% load i18n %}

{% block content %}


<dl  class="dl-horizontal">
  <dt> {% trans 'Title'%}  </dt>
  <dd>{{ incident.title }}</dd>
    
  <dt> {% trans 'Date Created'%} </dt>
  <dd>{{ incident.date_created }}</dd>
    
  <dt> {% trans 'Date Modified'%} </dt>
  <dd>{{ incident.date_modified }}</dd>
    
  <dt> {% trans 'Warden' %} </dt>
  <dd>{{ incident.warden_name }}</dd>
    
  <dt> {% trans 'Senior Warden'%} </dt>
  <dd>{{ incident.senior_warden }}</dd>
    
  <dt> {% trans 'Site'%} </dt>
  <dd>{{ incident.site }}</dd>
    
  <dt> {% trans 'Halls'%} </dt>
  <dd>{{ incident.halls }}</dd>
    
  <dt> {% trans 'Incident Type'%} </dt>
  <dd>{{ incident.incident_type }}</dd>
    
  <dt> {% trans 'Status'%} </dt>
  <dd>{{ incident.Case_Status }}</dd>
    
  <dt> {% trans 'Description'%} </dt>
  <dd>{{ incident.description }}</dd>
    
  <dt> {% trans 'Notes To'%} </dt>
  <dd>{{ incident.notes_to }}</dd>
    
  <dt> {% trans 'Notes By'%} </dt>
  <dd> {{ incident.notes_by }} </dd>
    
  <dt> {% trans 'Warning Issued'%} </dt>
  <dd>{{ incident.warning_issued }}</dd>
    
  <dt> {% trans 'Disciplinary required'%} </dt>
  <dd>{{ incident.Disciplinary_required }}</dd>
    
  <dt> {% trans 'Disciplinary called by'%} </dt>
  <dd>{{ incident.disciplinary_called_by }}</dd>
    
  <dt> {% trans 'Disciplinary date'%} </dt>
  <dd>{{ incident.disciplinary_date }}</dd>
    
  <dt> {% trans 'Student'%} </dt>
  <dd>{{ incident.student }}</dd>
    
  <dt> {% trans 'Accomplices'%} </dt>
  <dd>{{ incident.accomplices }}</dd>
    
  <dt> {% trans 'Complainant'%} </dt>
  <dd>{{ incident.complainant }}</dd>
    
  <dt> {% trans 'Witnesses'%} </dt>
  <dd>{{ incident.witnesses }}</dd>

</dl>

<div class="btn-group" role="group" aria-label="...">

  <a href="{% url 'update' incident.pk %}" type="button" class="btn btn-default">Edit</a>
</div>
{% endblock %}

wardenslog/wardens/templates/wardens/form.html
{% extends 'wardens/base.html' %}
{% load bootstrap3 %}
{% load i18n %}



{% block content %}
<form action="{{ action }}" method="POST">
{% csrf_token %}
    <ul>
        {% for field in form %}
        {{ field }}
        {% endfor %}
    </ul>
<input type="submit" value="Submit"/>


 </form>
    {% endblock %}

wardenslog/wardens/templates/wardens/incident.html
{%  extends 'wardens/base.html' %}

wardenslog/wardens/templates/wardens/incident_form.html
{% extends 'wardens/base.html' %}
{% load bootstrap3 %}
{% load i18n %}


{% block content %}
    {% bootstrap_form_errors form %}
<h3> {%  trans 'Please fill out the below form with the necessary details regarding the incident' %}</h3><br>
<form action="." method="post">

    {% bootstrap_field form.title %}
    {% bootstrap_field form.warden_name %}
    {% bootstrap_field form.senior_warden %}
    {% bootstrap_field form.site %}
    {% bootstrap_field form.halls %}
    {% bootstrap_field form.incident_type %}
    {% bootstrap_field form.case_status %}
    {% bootstrap_field form.description %}
    {% bootstrap_field form.notes_to %}
    {% bootstrap_field form.notes_by %}
    {% bootstrap_field form.warning_issued %}
    {% bootstrap_field form.disciplinary_required %}
    <div class="disc-group">
    {% bootstrap_field form.disciplinary_called_by %}
    {% bootstrap_field form.disciplinary_date %}
        </div>
    {% bootstrap_field form.student %}
    {% bootstrap_field form.complainant %}
    {% bootstrap_field form.accomplices %}
    {% bootstrap_field form.witnesses %}




    {% csrf_token %}
    <button type="submit" class="btn btn-primary">
    {% trans 'Create Report' %}
    </button>



<script>
$(document).ready(function () {
    $('#id_disciplinary_required').on('change', function () {
        if (this.value == 'Yes') {
            $('.disc-group').show(1000);
        } else {
            $('.disc-group').hide(1000)
        }

    });
});

</script>
    </form>
{% endblock %}

wardenslog/wardens/templates/wardens/login.html
{% extends 'wardens/base.html' %}



{% block content %}
<form action="{{ action }}" method="POST">
{% csrf_token %}
    <ul>
        {% for field in form %}
        {{ field }}
        {% endfor %}
    </ul>
<input type="submit" value="Submit"/>
{# form does not submit #}
<button type="submit" form="UserForm" value="Submit">Submit</button>


{% endblock %}

wardenslog/wardens/templates/wardens/logout.html
{% extends 'wardens/base.html' %}
{% load i18n %}
{% load bootstrap3 %}

{% block content %}
<form action="{{ action }}" method="POST" style="margin: auto; width: 50%">
{% csrf_token %}
{% bootstrap_form form %}
{% buttons %}
<button type="submit" class="btn btn-primary">
    {% trans 'Submit' %}
    </button>
{% endbuttons %}

{% endblock %}

wardenslog/wardens/templates/wardens/required.html
{%  extends 'wardens/base.html' %}

{% load i18n %}

{% block content %}
    <h1> {% trans 'Required' %} </h1>
 <table id="example" class="table table-striped table-bordered" cellspacing="0" width="100%">
    <thead>
        <tr>
        <th> {% trans 'Status' %} </td>
        <th> {% trans 'Title' %}  </th>
        <th> {% trans 'Date Created' %} </th>
        <th> {% trans 'Warden Name'%}</th>
        <th> {% trans 'Disciplinary Required' %}</th>
        <th> {% trans 'Disciplinary called by' %}</th>
        <th> {% trans 'Disciplinary date' %}</th>
        <th> {% trans 'View' %}</th>

    </tr>
    </thead>
    <tbody>
        {% for item in results %}
    <tr>
    <td>{{ item.case_status }}</td>
    <td>{{ item.title }}</td>
    <td>{{ item.date_created }}</td>
    <td>{{ item.warden_name }}</td>
    <td>{{ item.disciplinary_required }}</td>
    <td>{{ item.disciplinary_called_by }}</td>
    <td>{{ item.disciplinary_date }}</td>
    <td><a href="{% url 'detail' item.pk  %}"> {% trans 'detail' %}</a></td>

    </tr>

    {% endfor %}
    </tbody>
    </table>
<script>
$(document).ready(function(){
   $('#example').DataTable();
});

</script>
{% endblock %}

wardenslog/wardens/templates/wardens/taken.html
{%  extends 'wardens/base.html' %}

{% load i18n %}

{% block content %}
    <h1> {% trans ' Taken' %}</h1>
 <table id="example" class="table table-striped table-bordered" cellspacing="0" width="100%">
    <thead>
        <tr>
        <th> {% trans 'Status' %} </td>
        <th> {% trans 'Title' %}  </th>
        <th> {% trans 'Date Created' %} </th>
        <th> {% trans 'Warden Name'%}</th>
        <th> {% trans 'Disciplinary Required' %}</th>
        <th> {% trans 'Disciplinary called by' %}</th>
        <th> {% trans 'Disciplinary date' %}</th>
        <th> {% trans 'View' %}</th>
    </tr>
    </thead>
    <tbody>
        {% for item in results %}
    <tr>
    <td>{{ item.case_status }}</td>
    <td>{{ item.title }}</td>
    <td>{{ item.date_created }}</td>
    <td>{{ item.warden_name }}</td>
    <td>{{ item.disciplinary_required }}</td>
    <td>{{ item.disciplinary_called_by }}</td>
    <td>{{ item.disciplinary_date }}</td>
    <td><a href="{% url 'detail' item.pk  %}"> {% trans 'detail' %}</a></td>

    </tr>

    {% endfor %}
    </tbody>
    </table>
<script>
$(document).ready(function(){
   $('#example').DataTable();
});

</script>
{% endblock %}

wardenslog/wardens/templates/wardens/wardens.html
{%  extends 'wardens/base.html' %}
{% load i18n %}

{% block h1 %}

{% endblock %}

{% block content %}

 <div class="button" style="display: block; text-align: center;line-height: 125px; margin-left: auto; margin-right: auto">
    <h1> {% trans 'Homepage' %} </h1>
    <a href="/wardens/incident/form" style="height: 150px; width: 150px; margin-right: 10px; text-align : center;line-height: 125px " type="button" class="btn btn-default">{% trans 'Incident Report' %}</a>
     <a href="/wardens/required" style="height: 150px; width: 150px; margin-right: 10px;line-height: 125px" type="button" class="btn btn-default">{% trans 'Disciplinary Required' %}</a>
     <a href="/wardens/taken" style="height: 150px; width: 150px; margin-right: 10px;line-height: 125px" type="button" class="btn btn-default">{% trans 'Disciplinary Taken' %}</a>
     <a href="/wardens/cases" style="height: 150px; width: 150px; margin-right: 10px;line-height: 125px " type="button" class="btn btn-default">{% trans 'Cases' %}</a>
</div>

{% endblock %}